seeds:
  - url: https://experiencewelcome.com/blog
    depth: 3
    scopeType: "domain"
    exclude:
      - https://experiencewelcome.com/privacy-policy.*
      - https://experiencewelcome.com/terms-of-service.*
      - https://www.experiencewelcome.com/privacy-policy.*
      - https://www.experiencewelcome.com/terms-of-service.*
      - https://app.experiencewelcome.com/.*
